import type { Metadata } from "next";
import "./globals.css";
import { ThemeScript } from "@/lib/theme/theme-script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeScript/>
      </head>
      <body className="font-sans">{children}</body>
    </html>
  );
}
